### ISSUE TITLE
foodcritic can't run as UndefinedConversionError

### ISSUE THREAD

**Issue by cjw0122** [Foodcritic/foodcritic#457] opened 2016-05-26 03:37 UTC
I used foodcritic installed along with ChefDK in windows 7,
my ruby version is:ruby 2.1.8p440 (2015-12-16 revision 53160) [i386-mingw32]
ChefDK version is: v0.14.25

exception is as below:

 `    C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in    'encode': "\xAA\xA8" from GBK to UTF-8 (Encoding::UndefinedConversionError)

```
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in 'initialize'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in 'new'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in 'parse'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/gherkin-3.2.0/lib/gherkin/dialect.rb:5:in '<module:Gherkin>'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/gherkin-3.2.0/lib/gherkin/dialect.rb:3:in '<top (required)>'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/gherkin-3.2.0/lib/gherkin/token_matcher.rb:1:in 'require_relative'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/gherkin-3.2.0/lib/gherkin/token_matcher.rb:1:in '<top (required)>'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/gherkin-3.2.0/lib/gherkin/parser.rb:3:in 'require_relative'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/gherkin-3.2.0/lib/gherkin/parser.rb:3:in '<top (required)>'
    from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cucumber-core-1.4.0/lib/cucumber/core/gherkin/parser.rb:1:in '<top (required)>'
    from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:1:in '<top (required)>'
    from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/foodcritic-6.3.0/lib/foodcritic.rb:2:in '<top (required)>'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/foodcritic-6.3.0/bin/foodcritic:2:in 'require_relative'
    from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/foodcritic-6.3.0/bin/foodcritic:2:in '<top (required)>'
    from C:/opscode/chefdk/bin/foodcritic:19:in 'load'
    from C:/opscode/chefdk/bin/foodcritic:19:in '<main>'
```

`

**Comment by tas50** [comment] 2017-04-08 20:24
@cjw0122 Can you come up with a reproduction case so we can track down exactly what code snippet is causing this. Without a distilled bit of code there's no way to track this down and fix it.

**Comment by tas50** [comment] 2017-12-01 17:35
Closing this out since we never got a response. If you want to provide an example of a failing cookbook I'd be happy to dig in.

**Closed** 2017-12-01 17:35 UTC
Labels: Discussion
